/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_omptools_h
#define _sf_omptools_h


/*------------------------------------------------------------*/
int omp_init();
/*< init OMP parameters >*/

#endif
