/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_parallel_h
#define _sf_parallel_h


#include "file.h"


#define SF_CMDLEN 4096


char** sf_split(sf_file inp          /* input file */, 
		int axis             /* split axis */,
		int nodes            /* number of CPUs */,
		int *tasks           /* number of tasks */,
		int ndim, off_t *n   /* [ndim] file dimensions */, 
		int argc, char**argv /* command-line arguments */);
/*< split the input file along the specified axis
  and generate parallel system commands >*/


void sf_out(sf_file out        /* output file */, 
	    int axis           /* join axis */,
	    const char *iname  /* name of the input file */);
/*< prepare output >*/


void sf_join(sf_file out /* output file */, 
	     int job     /* job number */);
/*< join outputs >*/


void sf_add(sf_file out, int jobs);
/*< add outputs >*/

#endif
