/* This file is automatically generated. DO NOT EDIT! */

#ifndef _aniang_h
#define _aniang_h


/*------------------------------------------------------------*/
float* psitti(vc3d *nn,
	      vc3d *qq,
	      vc3d *tt,
	      vc3d *aa,
	      float tht,   /* reflection angle */
	      float phi,   /* reflection azimuth */
	      sf_axis aps, /* psi axis */
	      float vep,   /* P velocity */
	      float ves,   /* S velocity */
	      float eps,   /* epsilon */
	      float dlt)   /* delta   */;
/*< deviation angle in TTI media >*/


/*------------------------------------------------------------*/
float anivel(float alp, /* alpha */
	     float vep, /* P velocity */
	     float ves, /* S velocity */
	     float eps, /* epsilon */
	     float dlt) /* delta */;
/*< return TTI velocity as a function of angle >*/


/*------------------------------------------------------------*/
vc3d polvect(float phi,
	     float tht,
	     vc3d *nn,
	     vc3d *aa);
/*<  >*/


/*------------------------------------------------------------*/
vc3d vcp3dfix(vc3d* U, vc3d* V);
/*< vector product of 3D vectors >*/

#endif
