/* This file is automatically generated. DO NOT EDIT! */

#ifndef _cam3_h
#define _cam3_h


#include <rsf.h>


#include "weutil.h"


/*------------------------------------------------------------*/
cam3d cam3_init(cub3d cub,
		int pmx,
		int pmy,
		int phx,
		int tmx,
		int tmy,
		int thx,
		float dsmax
    );
/*< initialize >*/


void cam3_close(cam3d cam);
/*< free allocated storage >*/


/*------------------------------------------------------------*/
void cam3_ssf(
    sf_complex       w /* frequency */,
    sf_complex   ***wx /* wavefield */,
    cub3d          cub,
    cam3d          cam,
    tap3d          tap,
    slo3d          slo,
    int            imz,
    int         ompith
    );
/*< Wavefield extrapolation by SSF >*/

#endif
