/* This file is automatically generated. DO NOT EDIT! */

#ifndef _camig3_h
#define _camig3_h


#include <rsf.h>


#include "weutil.h"


/*------------------------------------------------------------*/
cub3d camig3_cube(bool   verb_,
		  sf_axis amx_,
		  sf_axis amy_,
		  sf_axis amz_,
		  sf_axis ahx_,
		  sf_axis alx_,
		  sf_axis aly_,
		  sf_axis aw_,
		  float   eps_,
		  int     ompnth_,
		  int     ompchunk_
    );
/*< initialize SR migration space >*/


/*------------------------------------------------------------*/
camoperator3d camig3_init(cub3d cub);
/*< initialize >*/


/*------------------------------------------------------------*/
void camig3_close(camoperator3d weop);
/*< free allocated storage >*/


/*------------------------------------------------------------*/
void camig3(camoperator3d weop,
	    cub3d cub,
	    cam3d cam,
	    tap3d tap,
	    slo3d slo,
	    bool  inv   /*      forward/adjoint flag */, 
	    sf_fslice data /* data  [nw][nhx][nmy][nmx] */,
	    sf_fslice imag /* image [nz][nhx][nmy][nmx] */);
/*< Apply migration/modeling >*/


/*------------------------------------------------------------*/
void cadtm3(camoperator3d weop,
	    cub3d cub,
	    cam3d cam,
	    tap3d tap,
	    slo3d slo,
	    bool  inv   /* forward/adjoint flag */, 
	    sf_fslice data /* data [nw][nmy][nmx] */,
	    sf_fslice wfld /* wfld [nw][nmy][nmx] */);
/*< Apply upward/downward datuming >*/


/*------------------------------------------------------------*/
void cawfl3(camoperator3d weop,
	    cub3d cub,
	    cam3d cam,
	    tap3d tap,
	    slo3d slo,
	    bool  inv   /* forward/adjoint flag */, 
	    sf_fslice data /*      data [nw][nmy][nmx] */,
	    sf_fslice wfld /* wavefield [nw][nmy][nmx] */);
/*< Save wavefield from downward continuation >*/

#endif
