/* This file is automatically generated. DO NOT EDIT! */

#ifndef _img3_h
#define _img3_h


#include <rsf.h>


#include "weutil.h"


/*------------------------------------------------------------*/
img3d img3_init(cub3d cub,
		sf_fslice imag,
		sf_fslice cigs,
		int jcx_,
		int jcy_,
		int jcz_
    );
/*< initialize I.C. >*/


/*------------------------------------------------------------*/
int cipmin(int nn,
	   int jc,
	   int nc,
	   int nh);
/*< find min eCIP index >*/


/*------------------------------------------------------------*/
int cipmax(int nn,
	   int jc,
	   int nc,
	   int nh);
/*< find max eCIP index >*/


/*------------------------------------------------------------*/
img3d img3o_init(cub3d cub,
		 sf_fslice imag,
		 sf_fslice cigs,
		 int jcx_,
		 int jcy_,
		 int jcz_
    );
/*< initialize zero-lag I.C. >*/


/*------------------------------------------------------------*/
img3d img3x_init(cub3d cub,
		 sf_fslice imag,
		 sf_fslice cigs,
		 int jcx_,
		 int jcy_,
		 int jcz_,
		 sf_axis ahx_,
		 sf_axis ahy_,
		 sf_axis ahz_
    );
/*< initialize x-lag I.C. >*/


/*------------------------------------------------------------*/
img3d img3t_init(cub3d cub,
		 sf_fslice imag,
		 sf_fslice cigs,
		 int jcx_,
		 int jcy_,
		 int jcz_,
		 sf_axis aht_
    );
/*< initialize t-lag I.C. >*/


/*------------------------------------------------------------*/
img3d img3e_init(cub3d cub,
		 sf_fslice imag,
		 sf_fslice cigs,
		 int jcx_,
		 int jcy_,
		 int jcz_,
		 sf_axis ahx_,
		 sf_axis ahy_,
		 sf_axis ahz_,
		 sf_axis aht_
    );
/*< initialize E.I.C. >*/


/*------------------------------------------------------------*/
img3d img3h_init(cub3d cub,
		 sf_fslice imag,
		 sf_fslice cigs,
		 int jcx_,
		 int jcy_,
		 int jcz_,
		 sf_axis ahh_,
		 sf_axis aha_,
		 sf_axis ahb_,
		 float vpvs_
    );
/*< initialize abs x-lag I.C. >*/


/*------------------------------------------------------------*/
void img3_cout(img3d img,
	       int i,
	       int ompith);
/*< update cigs on disk >*/


/*------------------------------------------------------------*/
void img3o(cub3d cub,
	   img3d img,
	   int iw,
	   int ompith);
/*< apply zero-lag I.C. >*/


/*------------------------------------------------------------*/
void oldimg3x(cub3d cub,
	   img3d img,
	   int iw,
	   int ompith);
/*< apply x-lag I.C. >*/


/*------------------------------------------------------------*/
void img3x(cub3d cub,
	   img3d img,
	   int iw,
	   int ompith);
/*< apply x-lag I.C. >*/


/*------------------------------------------------------------*/
void img3t(cub3d cub,
	   img3d img,
	   int iw,
	   int ompith);
/*< apply t-lag I.C. >*/


/*------------------------------------------------------------*/
void oldimg3e(cub3d cub,
	   img3d img,
	   int iw,
	   int ompith);
/*< apply E.I.C. >*/


/*------------------------------------------------------------*/
void img3e(cub3d cub,
	   img3d img,
	   int iw,
	   int ompith);
/*< apply E.I.C. >*/


/*------------------------------------------------------------*/
void img3h(cub3d cub,
	   img3d img,
	   int iw,
	   int ompith);
/*< apply abs-lag I.C. >*/


/*------------------------------------------------------------*/
void img3o_close(cub3d cub,
		 img3d img,
		 sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate zero-lag I.C. >*/


/*------------------------------------------------------------*/
void img3t_close(cub3d cub,
		 img3d img,
		 sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate t-lag I.C. >*/


/*------------------------------------------------------------*/
void img3h_close(cub3d cub,
		 img3d img,
		 sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate abs-lag I.C. >*/


/*------------------------------------------------------------*/
void img3x_close(cub3d cub,
		 img3d img,
		 sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate x-lag I.C. >*/


/*------------------------------------------------------------*/
void img3e_close(cub3d cub,
		 img3d img,
		 sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate x-lag I.C. >*/


/*------------------------------------------------------------*/
void img3_close(cub3d cub,
		img3d img);
/*< deallocate >*/


/*------------------------------------------------------------*/
void img3store(cub3d cub,
	       img3d img,
	       int imz,
	       sf_complex ***ww_s,
	       sf_complex ***ww_r,
	       int ompith
    );
/*< store wavefield >*/

#endif
