/* This file is automatically generated. DO NOT EDIT! */

#ifndef _slow3_h
#define _slow3_h


#include "weutil.h"


/*------------------------------------------------------------*/
slo3d slow3_init(cub3d   cub,
		 sf_fslice  slice_,   /* slowness slice */
		 int     nrmax,   /* maximum number of references */
		 float   dsmax,
		 float  twoway
    );
/*< initialize slowness >*/


/*------------------------------------------------------------*/
int slow3(int nr           /* maximum number of references */, 
	  float ds         /* minimum slowness separation */, 
	  int ns           /* number of slownesses */, 
	  const float* ss  /* [ns] slowness array */, 
	  float* sr        /* [nr] reference slownesses squared */);
/*< compute reference slownesses, return their number >*/


/*------------------------------------------------------------*/
void slow3_close( slo3d slo);
/*< close slowness >*/


/*------------------------------------------------------------*/
void slow3_advance( cub3d cub,
		    slo3d slo,
		    int ompith);
/*< close slowness >*/


/*------------------------------------------------------------*/
void slow3_twoway( cub3d     cub,
		   slo3d     slo,
		   float ***slow,
		   int    ompith);
/*< close slowness >*/

#endif
