/* This file is automatically generated. DO NOT EDIT! */

#ifndef _srmod3_h
#define _srmod3_h


#include <rsf.h>


#include "weutil.h"


/*------------------------------------------------------------*/
cub3d srmod3_cube(bool    verb_,
		  sf_axis amx_,
		  sf_axis amy_,
		  sf_axis amz_,
		  sf_axis alx_,
		  sf_axis aly_,
		  sf_axis aw_,
		  sf_axis ae_,
		  float   eps_,
		  int     ompnth_,
		  int     ompchunk_
    );
/*< initialize SR migration space >*/


/*------------------------------------------------------------*/
ssroperator3d srmod3_init(cub3d cub);
/*< initialize SR modeling >*/


/*------------------------------------------------------------*/
void srmod3_close(ssroperator3d weop);
/*< free allocated storage >*/


/*------------------------------------------------------------*/
void srmod3(ssroperator3d weop,
	    cub3d cub,
	    ssr3d ssr,
	    tap3d tap,
	    slo3d s_s,
	    slo3d s_r,
	    sf_fslice swfl /* source   data [nw][ny][nx] */,
	    sf_fslice rwfl /* receiver data [nw][ny][nx] */,
	    sf_fslice refl
    );
/*< apply SR modeling >*/

#endif
