/* This file is automatically generated. DO NOT EDIT! */

#ifndef _taper3_h
#define _taper3_h


#include "weutil.h"


/*------------------------------------------------------------*/
tap3d taper_init(int n1_,
		 int n2_,
		 int n3_,
		 int   nt1_, 
		 int   nt2_, 
		 int   nt3_ /* taper lengths */,
		 bool  b1_,
		 bool  b2_,
		 bool  b3_);
/*< 3-D initialize >*/


/*------------------------------------------------------------*/
void taper_report(tap3d tap);
/*< report taper parameters >*/


/*------------------------------------------------------------*/
void taper2d_close(tap3d tap);
/*< 2-D free allocated storage >*/


/*------------------------------------------------------------*/
void taper3d_close(tap3d tap);
/*< 3-D free allocated storage >*/


/*------------------------------------------------------------*/
void taper2d(sf_complex **tt  /* [n2][n1] tapered array (in and out) */,
	     tap3d tap);
/*< 2-D taper >*/


/*------------------------------------------------------------*/
void taper3d(sf_complex*** tt /* [n3][n2][n1] tapered array (inout) */,
	     tap3d tap);
/*< 3-D taper >*/

#endif
