/* This file is automatically generated. DO NOT EDIT! */

#ifndef _wei_h
#define _wei_h


#include <rsf.h>


#include "weiutl.h"


/*------------------------------------------------------------*/
weicub3d wei_cube(bool verb_,
		  int   ompnth_);
/*< initialize SR migration space >*/


/*------------------------------------------------------------*/
void wei_report(weicub3d cub);
/*< report cube >*/


/*------------------------------------------------------------*/
void weidat_inp(weicub3d cub,
		sf_file Fdat);
/*< input data dimensions >*/


/*------------------------------------------------------------*/
void gensou_inp(weicub3d cub,
                sf_file Fdat);
/*< input generailized source dimensions >*/


/*------------------------------------------------------------*/
void weieic_inp(weicub3d cub,
		sf_file Fcoo);
/*< input EIC parameters >*/


/*------------------------------------------------------------*/
void weihic_inp(weicub3d cub,
		sf_file Fcoo);
/*< input HIC parameters >*/


/*------------------------------------------------------------*/
void weiwfl_inp(weicub3d cub,
                sf_file Fwfl);
/*< input wavefield dimensions >*/


/*------------------------------------------------------------*/
void weiwfl_out(weicub3d cub,
		sf_file Fwfl);
/*< output wfl >*/


/*------------------------------------------------------------*/
void weidat_out(weicub3d cub,
		sf_file Fwfl);
/*< output dat >*/


/*------------------------------------------------------------*/
void weicic_out(weicub3d cub,
		sf_file Fcic);
/*< output cic >*/


/*------------------------------------------------------------*/
void weific_out(weicub3d cub,
		sf_file Fcic);
/*< output cic >*/


/*------------------------------------------------------------*/
void weieic_out(weicub3d cub,
		sf_file Feic);
/*< output EIC >*/


/*------------------------------------------------------------*/
weiop3d weiwfl_init(weicub3d cub);
/*< initialize weiwfl >*/


/*------------------------------------------------------------*/
weiop3d weidtm_init(weicub3d cub);
/*< initialize weidtm >*/


/*------------------------------------------------------------*/
weiop3d weicic_init(weicub3d cub);
/*< initialize CIC mig >*/


/*------------------------------------------------------------*/
weiop3f weific_init(weicub3d cub);
/*< initialize FIC mig >*/


/*------------------------------------------------------------*/
weiop3d weihic_init(weicub3d cub);
/*< initialize HIC mig >*/


/*------------------------------------------------------------*/
weiop3d weieic_init(weicub3d cub);
/*< initialize EIC mig >*/


/*------------------------------------------------------------*/
void weiwfl_close(weiop3d weop);
/*< free weiwfl storage >*/


/*------------------------------------------------------------*/
void weidtm_close(weiop3d weop);
/*< free weidtm storage >*/


/*------------------------------------------------------------*/
void weicic_close(weiop3d weop);
/*< free CIC mig storage >*/


/*------------------------------------------------------------*/
void weific_close(weiop3f weop);
/*< free FIC mig storage >*/


/*------------------------------------------------------------*/
void weihic_close(weiop3d weop);
/*< free HIC mig storage >*/


/*------------------------------------------------------------*/
void weieic_close(weiop3d weop);
/*< free EIC mig storage >*/


/*------------------------------------------------------------*/
void weiwfl(weiop3d weop,
	    weicub3d cub,
	    weissr3d ssr,
	    weitap3d tap,
	    weislo3d slo,
	    sf_file Fdat,
	    sf_file Fwfl,
	    bool causal);
/*< wei wavefield >*/


/*------------------------------------------------------------*/
void genwfl(weiop3d weop,
            weicub3d cub,
            weissr3d ssr,
            weitap3d tap,
            weislo3d slo,
            weico3d eico,
            sf_file Fsou,
            sf_file Fwfl,
            bool    down,
            bool   causal);
/*< wei wavefield >*/


/*------------------------------------------------------------*/
void adjwfl(weiop3d weop,
            weicub3d cub,
            weissr3d ssr,
            weitap3d tap,
            weislo3d slo,
            sf_file Fsou,
            sf_file Fwfl,
            bool    down,
            bool   causal);
/*< wei wavefield >*/


/*------------------------------------------------------------*/
void gradient(weicub3d cub,
              sf_file Fsou,
              sf_file Frec,
              sf_file Fgrd,
	      bool conj);
/*< wei gradient >*/


/*------------------------------------------------------------*/
void weidtm(weiop3d weop,
	    weicub3d cub,
	    weissr3d ssr,
	    weitap3d tap,
	    weislo3d slo,
	    sf_file Fdat,
	    sf_file Fwfl,
	    bool causal);
/*< wei wavefield >*/


/*------------------------------------------------------------*/
void weific(weiop3f weop,
	    weicub3d cub,
	    weissr3d ssr,
	    weitap3d tap,
	    weislo3d slo,
	    sf_file Fsou,
	    sf_file Frec,
	    sf_file Fcic);
/*< FIC migration >*/


/*------------------------------------------------------------*/
void weicic(weiop3d weop,
	    weicub3d cub,
	    weissr3d ssr,
	    weitap3d tap,
	    weislo3d slo,
	    sf_file Fsou,
	    sf_file Frec,
	    sf_file Fcic);
/*< CIC migration >*/


/*------------------------------------------------------------*/
void weizocic(weiop3d weop,
            weicub3d cub,
            weissr3d ssr,
            weitap3d tap,
            weislo3d slo,
            sf_file Fdat,
            sf_file Fcic);
/*< zero-offset migration >*/


/*------------------------------------------------------------*/
void weizomod(weiop3d weop,
            weicub3d cub,
            weissr3d ssr,
            weitap3d tap,
            weislo3d slo,
            sf_file Fdat,
            sf_file Fcic);
/*< zero-offset modeling >*/


/*------------------------------------------------------------*/
weico3d weicoo_init(weicub3d cub,
		    sf_file Fcoo);
/*< EIC coordinates >*/


/*------------------------------------------------------------*/
weico3d gencoo_init(weicub3d cub,
                    sf_file Fcoo);
/*< EIC coordinates >*/


/*------------------------------------------------------------*/
void wei_hicindex(weicub3d cub,
		  weico3d eico);
/*< set cc indices >*/


/*------------------------------------------------------------*/
void wei_timelag(weicub3d cub,
		 weico3d eico);
/*< time delay init >*/


/*------------------------------------------------------------*/
void weicoo_close(weico3d eico);
/*< EIC coordinates close >*/


/*------------------------------------------------------------*/
void gencoo_close(weico3d eico);
/*< EIC coordinates close >*/


/*------------------------------------------------------------*/
void weihic(weiop3d weop,
	    weicub3d cub,
	    weissr3d ssr,
	    weitap3d tap,
	    weislo3d slo,
	    weico3d eico,
	    sf_file Fsou,
	    sf_file Frec,
	    sf_file Fcic,
	    sf_file Feic);
/*< HIC migration >*/


/*------------------------------------------------------------*/
void weieic(weiop3d weop,
	    weicub3d cub,
	    weissr3d ssr,
	    weitap3d tap,
	    weislo3d slo,
	    weico3d eico,
	    sf_file Fsou,
	    sf_file Frec,
	    sf_file Fcic,
	    sf_file Feic);
/*< EIC migration >*/


/*------------------------------------------------------------*/
void weicic_write(weiop3d weop,
		  weicub3d cub,
		  sf_file Fcic);
/*< write CIC >*/


/*------------------------------------------------------------*/
void weific_write(weiop3f weop,
		  weicub3d cub,
		  sf_file Fcic);
/*< write CIC >*/


/*------------------------------------------------------------*/
void weihic_write(weiop3d weop,
		  weicub3d cub,
		  sf_file Feic);
/*< write HIC >*/


/*------------------------------------------------------------*/
void weieic_write(weiop3d weop,
		  weicub3d cub,
		  sf_file Feic);
/*< write EIC >*/


/*------------------------------------------------------------*/
void weicic_one(weiop3d weop,
		weicub3d cub,
		int ompith,
		int iz);
/*< apply CIC at one z >*/


/*------------------------------------------------------------*/
void weizocic_one(weiop3d weop,
                weicub3d cub,
                int ompith,
                int iz);
/*< apply CIC at one z >*/


/*------------------------------------------------------------*/
void weific_one(weiop3f weop,
		weicub3d cub,
		int ompith,
		int iz,
		int iw);
/*< apply FIC at one z >*/


/*------------------------------------------------------------*/
void weihic_one(weiop3d weop,
		weicub3d cub,
		weico3d eico,
		int ompith,
		int iz,
		int iw);
/*< apply HIC at one z >*/


/*------------------------------------------------------------*/
void gensou_inject(sf_complex **wfl,
                   sf_complex **sou,
		   weico3d  eico,
		   int iz,
		   int iw);
/*< inject generalized source into wavefield >*/


/*------------------------------------------------------------*/
void for_cic(weicub3d cub,
	     sf_complex ***swfl,
	     sf_complex ***rwfl,
	     sf_complex  ***cic,
	     bool conj);
/*< apply forward C.I.C. >*/


/*------------------------------------------------------------*/
void weicic_apply(weiop3d weop,
		  weicub3d cub);
/*< apply CIC >*/


/*------------------------------------------------------------*/
void weieic_apply(int jw,
		  int ibk,
		  weiop3d weop,
		  weico3d eico,
		  weicub3d cub);
/*< apply EIC >*/

#endif
