/* This file is automatically generated. DO NOT EDIT! */

#ifndef _weiajs_h
#define _weiajs_h


#include <rsf.h>


#include "wei.h"
#include "weitap.h"
#include "weislo.h"
#include "weissr.h"
#include "weiajs.h"
#include "weiutl.h"


/*------------------------------------------------------------*/
weiop3d weihicajs_init(weicub3d cub);
/*< initialize HIC mig >*/


/*------------------------------------------------------------*/
void mvahic_inp(weicub3d cub,
                sf_file Feic,
                sf_file Fcoo);
/*< input HIC parameters from files >*/


/*------------------------------------------------------------*/
void adjsou(weicub3d cub,
            weico3d eico,
            sf_file Feic,
            sf_file Fbwf,
            sf_file Faso,
	    bool conj);
/*< adjoint source construction >*/


/*------------------------------------------------------------*/
void adj_eic(weicub3d cub,
             weico3d eico,
	     sf_complex ***swfl,
	     sf_complex ***asou,
	     sf_complex *****cip,
	     bool cjg,
	     int iw);
/*< apply adjoint E.I.C. >*/


/*------------------------------------------------------------*/
void weihicajs_close(weiop3d weop);
/*< free HIC adjoint source storage >*/


/*------------------------------------------------------------*/
void weihicajs(weiop3d weop,
	       weicub3d cub,
	       weico3d eico,
	       sf_file Feic,
	       sf_file Fbwf,
	       sf_file Faso,
	       bool conj);
/*< HIC adjoint source construction >*/


/*------------------------------------------------------------*/
void weihicajs_apply(weiop3d weop,
		     weicub3d cub,
		     weico3d eico,
		     int ompith,
		     int iw,
		     int iz,
		     bool cjg);
/*< apply adjoint E.I.C. >*/

#endif
