/* This file is automatically generated. DO NOT EDIT! */

#ifndef _weissr_h
#define _weissr_h


#include <rsf.h>


#include "weiutl.h"


/*------------------------------------------------------------*/
weissr3d weissr_init(weicub3d cub,
                     weislo3d slo);
/*< initialize >*/


/*------------------------------------------------------------*/
void weissr_close(weicub3d cub,
		  weissr3d ssr);
/*< free allocated storage >*/


/*------------------------------------------------------------*/
void weissr( sf_complex          w, 
	     sf_complex       **wx,
	     weicub3d          cub,
	     weissr3d          ssr,
	     weislo3d          slo,
	     int                iz,
	     int            ompith
    );
/*< Wavefield extrapolation by SSF >*/


/*------------------------------------------------------------*/
void weissr1(sf_complex          w,
             sf_complex       **wx,
             weicub3d          cub,
             weissr3d          ssr,
             weislo3d          slo,
             int                iz,
             int            ompith,
             bool               adj
    );
/*< Wavefield extrapolation by SSF >*/

#endif
