/* This file is automatically generated. DO NOT EDIT! */

#ifndef _weitap_h
#define _weitap_h


#include "weiutl.h"


/*------------------------------------------------------------*/
weitap3d weitap_init(weicub3d cub);
/*< taper initialize >*/


/*------------------------------------------------------------*/
void weitap_close(weitap3d tap);
/*< 2-D free allocated storage >*/


/*------------------------------------------------------------*/
void weitap(sf_complex **tt  /* [n2][n1] tapered array (in and out) */,
	    weitap3d tap);
/*< 2-D taper >*/

#endif
