/* This file is automatically generated. DO NOT EDIT! */

#ifndef _zomig3_h
#define _zomig3_h


#include <rsf.h>


#include "weutil.h"


/*------------------------------------------------------------*/
cub3d zomig3_cube(bool    verb_,
		  sf_axis amx_,
		  sf_axis amy_,
		  sf_axis amz_,
		  sf_axis alx_,
		  sf_axis aly_,
		  sf_axis aw_,
		  sf_axis ae_,
		  float   eps_,
		  int     ompnth_,
		  int     ompchunk_
    );
/*< initialize SR migration space >*/


/*------------------------------------------------------------*/
ssroperator3d zomig3_init(cub3d cub);
/*< initialize >*/


/*------------------------------------------------------------*/
void zomig3_close(ssroperator3d weop);
/*< free allocated storage >*/


/*------------------------------------------------------------*/
void zomig3(ssroperator3d weop,
	    cub3d cub,
	    ssr3d ssr,
	    tap3d tap,
	    slo3d slo,
	    bool  inv   /* forward/adjoint flag */, 
	    sf_fslice data /* data  [nw][nmy][nmx] */,
	    sf_fslice imag /* image [nz][nmy][nmx] */);
/*< Apply migration/modeling >*/


/*------------------------------------------------------------*/
void zodtm3(ssroperator3d weop,
	    cub3d cub,
	    ssr3d ssr,
	    tap3d tap,
	    slo3d slo,
	    bool inv    /* forward/adjoint flag */, 
	    bool causal,
	    sf_fslice data /* data [nw][nmy][nmx] */,
	    sf_fslice wfld /* wfld [nw][nmy][nmx] */);
/*< Apply upward/downward datuming >*/


/*------------------------------------------------------------*/
void zowfl3(ssroperator3d weop,
	    cub3d cub,
	    ssr3d ssr,
	    tap3d tap,
	    slo3d slo,
	    bool inv    /* forward/adjoint flag */, 
	    bool causal,
	    sf_fslice data /*      data [nw][nmy][nmx] */,
	    sf_fslice wfld /* wavefield [nw][nmy][nmx] */);
/*< Save wavefield from downward continuation >*/

#endif
