ENV = {'PATH': '/opt/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin', 'LD_LIBRARY_PATH': '', 'PATHOSX': '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin', 'HOME': '/Users/lewisli'}
RSFROOT = '/Volumes/Communal/OSX/code-dev/RSF'
AR = 'ar'
JPEG = None
OPENGL = []
OPENGLFLAGS = ' -framework AGL -framework OpenGL -framework GLUT'
OPENGLPATH = None
MPICC = None
MPICXX = None
SPARSEPATH = None
SPARSELIBS = None
FFTW = None
OMP = False
PTHREADS = True
BLAS = None
LAPACK = True
PPM = None
TIFF = None
GD = None
PLPLOT = None
FFMPEG = None
CAIROPNG = None
SFPEN = 'oglpen'
DYNLIB = ''
CC = 'gcc'
CFLAGS = '-O2 -x c -std=gnu99 -Wall -pedantic'
CPPPATH = ['/opt/local/include']
CPPDEFINES = ['NO_BLAS']
LIBPATH = ['/opt/local/lib']
LIBS = ['m', 'mx']
LINKFLAGS = ['-framework', 'Accelerate']
XLIBPATH = ['/opt/X11/lib']
XLIBS = ['Xaw', 'Xt', 'X11']
XINC = ['/opt/X11/include']
API = ['c++']
CXX = 'g++'
CXXFLAGS = '-O2 -Wall -pedantic'
F77 = 'gfortran'
FORTRAN = 'gfortran'
F90 = 'gfortran'
JAVAC = 'javac'
CUDA_TOOLKIT_PATH = '/usr/local/CUDA'
NVCC = '/usr/local/CUDA/bin/nvcc'
NUMPY = None
SWIG = None
