ENV = {'PATH': '/usr/local/bin:/opt/bin:/bin:/usr/bin', 'LD_LIBRARY_PATH': ''}
RSFROOT = '/home/lewisli/code-dev/RSF'
AR = 'ar'
JPEG = 'jpeg'
OPENGL = None
OPENGLFLAGS = None
OPENGLPATH = None
MPICC = None
MPICXX = None
SPARSEPATH = None
SPARSELIBS = None
FFTW = 'fftw3f'
OMP = True
PTHREADS = True
BLAS = None
LAPACK = None
PPM = None
TIFF = 'tiff'
GD = 'gd'
GIFANIM = True
PLPLOT = None
FFMPEG = 'avcodec'
FFMPEGPATH = '/usr/include/libavcodec'
CAIROPNG = 'cairo'
CAIROSVG = 'cairo'
CAIROPDF = 'cairo'
CAIROPATH = '/usr/include/cairo'
SFPEN = 'xtpen'
DYNLIB = ''
CC = 'gcc'
CFLAGS = '-O2 -x c -std=gnu99 -Wall -pedantic -fopenmp'
CPPPATH = []
CPPDEFINES = ['NO_BLAS']
LIBPATH = []
LIBS = ['m', 'gomp', 'fftw3f']
LINKFLAGS = ['-pthread', '-fopenmp']
XLIBPATH = ['/usr/lib/X11']
XLIBS = ['Xaw', 'Xt', 'X11']
XINC = ['/usr/include']
API = ['c++']
CXX = 'g++'
CXXFLAGS = '-O2 -Wall -pedantic -fopenmp'
F77 = 'gfortran'
FORTRAN = 'gfortran'
F90 = 'gfortran'
JAVAC = 'javac'
CUDA_TOOLKIT_PATH = None
NUMPY = None
SWIG = None
