/* This file is automatically generated. DO NOT EDIT! */

#ifndef _allp2_h
#define _allp2_h


typedef struct Allpass2 *allpas2;
/* abstract data type */


allpas2 allpass2_init(int nw         /* filter order */, 
		       int nj         /* filter step */, 
		       int nx, int ny /* data size */, 
		       float **pp     /* dip [ny][nx] */);
/*< Initialize >*/


void allpass2_close(allpas2 ap);
/*< free allocated storage >*/


void allpass22_init (allpas2 ap1);
/*< Initialize linear operator >*/


void allpass21_lop (bool adj, bool add, int n1, int n2, float* xx, float* yy);
/*< PWD as linear operator >*/


void allpass21 (bool der          /* derivative flag */, 
		const allpas2 ap /* PWD object */, 
		float** xx        /* input */, 
		float** yy        /* output */);
/*< plane-wave destruction >*/

#endif
