/* This file is automatically generated. DO NOT EDIT! */

#ifndef _apfilt_h
#define _apfilt_h


void apfilt_init(int nw /* filter order */);
/*< initialize >*/


void apfilt_close(void);
/*< free allocated storage >*/


void passfilter (float p  /* slope */, 
		 float* a /* output filter [n+1] */);
/*< find filter coefficients >*/


void aderfilter (float p  /* slope */, 
		 float* a /* output filter [n+1] */);
/*< find coefficients for filter derivative >*/

#endif
