/* This file is automatically generated. DO NOT EDIT! */

#ifndef _diplet_h
#define _diplet_h


void diplet_init(int n1      /* trace length */, 
		 int n2      /* number of traces */,
		 int np1     /* number of slopes */,
		 float ***p1 /* slopes */,
		 float ***m1 /* data mask */,
		 bool inv    /* inversion flag */, 
		 float eps   /* regularization parameter */,
		 int order   /* accuracy order */,
		 char type   /* transform type */);
/*< allocate space >*/


void diplet_close(void);
/*< deallocate space >*/


void diplet_lop(bool adj, bool add, int nx, int ny, float *x, float *y);
/*< linear operator >*/

#endif
