/* This file is automatically generated. DO NOT EDIT! */

#ifndef _div2_h
#define _div2_h


void div2_init(int n1, int n2     /* data dimensions */, 
	       float f1, float f2 /* smoothing */, 
	       int niter1         /* number of iterations */, 
	       bool gauss1        /* if exact gaussian */,
	       bool verb          /* verbosity flag */);
/*< initialize >*/


void div2_close (void);
/*< free allocated storage >*/


void div2 (float* num, float* den,  float* rat);
/*< smooth division: rat=num/den >*/

#endif
