/* This file is automatically generated. DO NOT EDIT! */

#ifndef _expont_h
#define _expont_h


#include <rsf.h>


void expont_init(int n1_in,int n2_in /* data size */, 
		 float *a1           /* filter component [n1*n2] */, 
		 float *b1           /* filter component [n1*n2] */);
/*< initialize >*/


void expont_lop (bool adj, bool add, int nx, int ny, float *xx, float *yy);
/*< linear operator >*/

#endif
