/* This file is automatically generated. DO NOT EDIT! */

#ifndef _expsignoi2_h
#define _expsignoi2_h


#include <rsf.h>


void expsignoi2_init (int m1,int m2 /* data size */, 
		      float eps1    /* signal/noise scaling */, 
		      float **aa    /* frequency filter [4][m1*m2] */);
/*< initialize >*/


void expsignoi2_close(void);
/*< free allocated storage >*/


void expsignoi2_lop (bool adj, bool add, int ns, int nd, 
		     float *sig /* signal */, float *dat /* data */);
/*< linear operator >*/

#endif
