/* This file is automatically generated. DO NOT EDIT! */

#ifndef _gauss2_h
#define _gauss2_h


void gauss2_init(int n1, int n2     /* data size */, 
		 float f1, float f2 /* smoothing radius */);
/*< initialize (call freqfilt2 afterwards) >*/


void gauss2_close(void);
/*< free allocated storage >*/

#endif
