/* This file is automatically generated. DO NOT EDIT! */

#ifndef _planesignoi_h
#define _planesignoi_h


#include <rsf.h>


void planesignoi_init (int nw           /* filter size */, 
		       int nj1, int nj2 /* dealiasing stretch */, 
		       int nx, int ny   /* data size */, 
		       float **nn       /* noise slope */, 
		       float **ss       /* signal slope */, 
		       float eps1       /* regularization parameter */);
/*< initialize >*/


void planesignoi_lop (bool adj, bool add, int ns, int nd, float *s, float *d);
/*< linear operator >*/


void planesignoi_close(void);
/*< free allocated storage >*/

#endif
