/* This file is automatically generated. DO NOT EDIT! */

#ifndef _predk_h
#define _predk_h


void predk_init(int nk          /* number of components */,
		int m1, int m2  /* data dimensions */, 
		float eps       /* regularization parameter */,
		int order       /* accuracy order */,
		float*** pk     /* slopes [nk][m1][m2] */);
/*< initialize >*/


void predk_close(void);
/*< free allocated storage >*/


void predk_lop(bool adj, bool add, int nx, int ny, float* x, float* y);
/*< linear operator >*/

#endif
