/* This file is automatically generated. DO NOT EDIT! */

#ifndef _pwsmooth_h
#define _pwsmooth_h


void pwsmooth_init(int ns      /* spray radius */,
		   int m1      /* trace length */,
		   int m2      /* number of traces */,
		   int order   /* PWD order */,
		   float eps   /* regularization */,
		   float **dip /* local slope */);
/*< initialize >*/


void pwsmooth_close(void);
/*< free allocated storage >*/


void pwsmooth_lop(bool adj, bool add, 
		  int nin, int nout, float* trace, float *smooth);
/*< linear operator >*/

#endif
