/* This file is automatically generated. DO NOT EDIT! */

#ifndef _pwspray_h
#define _pwspray_h


int pwspray_init(int nr      /* spray radius */, 
		 int nt      /* trace length */, 
		 int n       /* number of traces */,
		 int order   /* PWD order */,
		 float eps   /* regularization */,
		 float **dip /* local slope */);
/*< initialize >*/


void pwspray_close(void);
/*< free allocated storage >*/


void pwspray_lop(bool adj, bool add, int n, int nu, float* u1, float *u);
/*< linear operator >*/

#endif
