/* This file is automatically generated. DO NOT EDIT! */

#ifndef _seislet_h
#define _seislet_h


void seislet_init(int n1      /* trace length */, 
		  int n2      /* number of traces */, 
		  bool inv1   /* inversion flag */, 
		  bool unit1  /* weighting flag */,
		  float eps   /* regularization parameter */,
		  int order   /* accuracy order */,
		  char type   /* transform type */);
/*< allocate space >*/


void seislet_set(float **dip /* local slope */);
/*< set local slope >*/


void seislet_close(void);
/*< deallocate space >*/


void seislet_lop(bool adj, bool add, int nx, int ny, float *x, float *y);
/*< linear operator >*/


void seislet_destruct(bool adj, bool add, int nx, int ny, float *x, float *y);
/*< linear operator >*/


void seislet_construct(bool adj, bool add, int nx, int ny, float *x, float *y);
/*< linear operator >*/

#endif
