/* This file is automatically generated. DO NOT EDIT! */

#ifndef _seisletk_h
#define _seisletk_h


void seisletk_init(int nk      /* number of components */,
		   int n1      /* trace length */, 
		   int n2      /* number of traces */, 
		   bool inv    /* inversion flag */, 
		   float eps   /* regularization parameter */,
		   int order   /* accuracy order */,
		   char type   /* transform type */,
		   float*** pk /* slopes [nk][m1][m2] */);
/*< initialize >*/


void seisletk_close(void);
/*< free allocated storage >*/


void seisletk_lop(bool adj, bool add, int nx, int ny, float* x, float* y);
/*< linear operator >*/

#endif
