/* This file is automatically generated. DO NOT EDIT! */

#ifndef _smoothshape_h
#define _smoothshape_h


void smoothshape_init(int n1, int n2        /* data size */,
		      int order             /* accuracy order */,
		      int rect1, int rect2  /* smoothing radius */,
		      float lam             /* operator scaling */,
		      float **dip           /* dip field */);
/*< initialize >*/


void smoothshape_close(void);
/*< free allocated storage >*/


void smoothshape(int niter     /* number of iterations */, 
		 float* weight /* data weighting */, 
		 float* data   /* input data */, 
		 float* der    /* output derivative */);
/*< find the derivative >*/

#endif
