/* This file is automatically generated. DO NOT EDIT! */

#ifndef _trisl_h
#define _trisl_h


#include <rsf.h>


void trisl_init(int m1, int m2       /* data dimensions */, 
		int rect1, int rect2 /* triangle radius */);
/*< initialize >*/


void trisl_set(float** p1 /* slope [m2][m1] */);
/*< set slopes >*/


void trisl_close(void);
/*< free allocated storage >*/


void trisl_lop(bool adj, bool add, int nx, int ny, float* x, float* y);
/*< linear operator >*/

#endif
