/* This file is automatically generated. DO NOT EDIT! */

#ifndef _twodip2_h
#define _twodip2_h


#include <rsf.h>


void twodip2_init(int nx, int ny     /* data size */, 
		  float fx, float fy /* smoothing radius */, 
		  bool sign1         /* if keep slope signs */,
		  bool gauss         /* Gaussian versus triangle smoothing */,
		  bool verb          /* verbosity flag */,
		  bool both          /* both slopes or one */);
/*< initialize >*/


void twodip2_close(void);
/*< free allocated storage >*/


void twodip2(int niter        /* number of iterations */, 
	     int nw           /* filter order */, 
	     int nj1, int nj2 /* dealisianing stretch */, 
	     bool verb        /* verbosity flag */, 
	     float *u         /* input data */, 
	     float** pq       /* output slopes */, 
	     bool *mask       /* mask for missing data */);
/*< estimate slopes >*/


void otherdip2(int niter        /* number of iterations */, 
	       int nw           /* filter order */, 
	       int nj1, int nj2 /* dealising stretch */, 
	       bool verb        /* verbosity flag */, 
	       float *u         /* input data */, 
	       float** pq       /* output slope */, 
	       bool *mask       /* mask for missing data */);
/*< estimate the second slope only >*/

#endif
