/* This file is automatically generated. DO NOT EDIT! */

#ifndef _twoplane2_h
#define _twoplane2_h


#include <rsf.h>


void twoplane2_init (int nw_in            /* filter size */, 
		     int nj1, int nj2     /* dealising stretch */, 
		     int nx_in, int ny_in /* data size */,
		     float **pp           /* first slope */, 
		     float **qq           /* second slope */);
/*< initialize >*/


void twoplane2_close(void);
/*< free allocated storage >*/


void twoplane2_lop (bool adj, bool add, int n1, int n2, float *xx, float *yy);
/*< linear operator >*/

#endif
