/* This file is automatically generated. DO NOT EDIT! */

#ifndef _cgsolver_h
#define _cgsolver_h


#include <rsf.h>


void cg_solve(	float **a /*matrix operator*/, 
	      	float *x /*initial vector and final output solution*/,
		float *b /*right hand side*/,
		int n /*matrix size*/,
		int iter /*iteration value*/);
/*< solver using conjugate gradient algorithm >*/

#endif
