/* This file is automatically generated. DO NOT EDIT! */

#ifndef _cholesky_h
#define _cholesky_h


void cholesky_dec(	float *a/*input matrix and output triangle matrix*/,
			int n/*matrix size*/);
/*< Cholesky decomposition >*/


void cholesky_solve(    float *l/*input triangle matrix*/, 
			float *d/*input right hand side and output solution*/, 
			int n/*matrix size*/);
/*< Solving equation >*/

#endif
