/* This file is automatically generated. DO NOT EDIT! */

#ifndef _csolver_h
#define _csolver_h


void csolve_init(kiss_fft_cpx **a,kiss_fft_cpx *b,int N);
/*< initiate complex solver >*/


void gaussel_csolve(kiss_fft_cpx *x, int niter);
/*< Gauss elimination complex solver >*/


void gs_csolve(kiss_fft_cpx *x, int niter);
/*< Gauss-Seidel iteration complex solver >*/


void jacobi_csolve(kiss_fft_cpx *x, int niter);
/*< Jacobi iteration iteration complex solver >*/


void sor_csolve(kiss_fft_cpx *x, int niter, float w);
/*< SOR iteration iteration complex solver >*/


void sd_csolve(kiss_fft_cpx *x, int niter);
/*< Steepest descent complex solver >*/

#endif
