/* This file is automatically generated. DO NOT EDIT! */

#ifndef _ffilter_h
#define _ffilter_h


void trapezoid_init(int n /*length of time series*/, 
		    float fn /*nyquist frequency*/, 
	 	    float *ff /*trapezoid key point frequency*/);
/*< initialize with data length >*/


void trapezoid_apply(float *xx /*input time series*/,
		     float *yy /*output time seires*/);
/*< applying trapezoid bandpass filter >*/

#endif
