/* This file is automatically generated. DO NOT EDIT! */

#ifndef _hilbert_h
#define _hilbert_h


void hilbert_t (float* trace /*input signal*/, 
		float* trace2 /*output hilbert data*/,
                int n1 /* trace length */);
/*< time domain tranform >*/


void hilbert_f (float* trace /*input signal*/, 
		float* trace2 /*output hilbert data*/,
                int n1 /* trace length */);
/*< frequency domain transform >*/


void hilbert_m (float* trace /*input signal*/, 
		float* trace2 /*output hilbert data*/,
                int nt1 /* trace length */, 
                int n1 /* transform length */, 
                int c1 /* filter parameter */);
/*< maximally flat hilbert transformer (MFHT) transform >*/

#endif
