/* This file is automatically generated. DO NOT EDIT! */

#ifndef _matoper_h
#define _matoper_h


#include <rsf.h>


void matmult_init (float** a);
/*< initialize with a pointer to a matrix >*/


void matmult_lop (bool adj, bool add, 
		  int nx, int ny, float* x, float*y);
/*< linear matrix multiplication operator >*/

#endif
