/* This file is automatically generated. DO NOT EDIT! */

#ifndef _medianutil_h
#define _medianutil_h


float medianfilter(float *temp,int nfw);
/*< get a median value >*/


void vecmedianfilter(float *temp1,/* input vector set */
		     int nfw,     /* width vector median filter */
		     int ns,      /* number of samples per vector*/
		     float *temp2 /* output vector */);
/*< get a median vector >*/


void bound1(float* tempt,float* extendt,int nfw,int n1,int n2,bool boundary);
/*<extend seismic data>*/


void bound2(float* temp2,float* temp3,int n1,int tempnfw,int j,bool boundary);
/*<extend temporary seismic data>*/


void bound3(float* tempt,
	    float* extendt,
	    int nfw1        /* Sample direction*/,
	    int nfw2        /* Trace direction */,
	    int n1,int n2,
	    bool boundary);
/*<extend seismic data>*/

#endif
