/* This file is automatically generated. DO NOT EDIT! */

#ifndef _radonutil_h
#define _radonutil_h


void hradon_init(int Nt, int Nh, int Nv, float Dt, float *V, float *H);
/*< Initialization for linear radon operator >*/


void hradon1(bool adj, bool add, int nx, int ny, float *x, float *y);
/*< hyperbolic radon operator >*/


void hradon(bool adj, bool add, int nx, int ny, float *x, float *y);
/*< hyperbolic radon operator >*/


void hradon_pcg(sf_operator oper, 
			float *d, 
			float *x, 
			int itmax_internal,
			int itmax_external, 
			int verb,
			float *misfit);
/*< Preconditioned CG for sparsity promotion hyperbolic radon transform >*/

#endif
