/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sdsolver_h
#define _sdsolver_h


#include <rsf.h>


void sd_solve(	float **a /*matrix operator*/, 
	      	float *x /*initial vector and final output solution*/,
		float *b /*right hand side*/,
		int n /*matrix size*/,
		int iter /*iteration value*/);
/*< solver using steepest descent algorithm >*/

#endif
