/* This file is automatically generated. DO NOT EDIT! */

#ifndef _solver_h
#define _solver_h


void gaussel_init (int size);
/*< initialize >*/


void gaussel_close (void);
/*< free allocated storage >*/


void gaussel_solve (float **a       /* matrix [size][size] */, 
		    const float *b  /* rhs [size] */, 
		    float *x        /* solution [size] */);
/*< solve a*x = b >*/

#endif
