/* This file is automatically generated. DO NOT EDIT! */

#ifndef _taup_h
#define _taup_h


float findmax(int ny, int nx, kiss_fft_cpx **c);
/*< find the max value >*/


void slant(float dt,int nt, int nx,float *gx, float pxmin, float dpx, int npx, float **data, float **taup, float **semb, float *sembp, float *sembpMax, float *fshift, float *fden);
/*< taup transform 
Direct mapping of seismic data to the domain of intercept
time and ray parameter -A plane-wave decomposition, Paul L. Stoffa, Geophysics, 1981 >*/


void shfs8r (float dx, int nxin, float fxin, float yin[], 
	float yinl, float yinr, int nxout, float fxout, float yout[]);
/*< shift a uniformly-sampled real function via a table of 8-coeff. sinc approximations. >*/


void mksinc (float d, int lsinc, float sinc[]);
/*< Compute least-squares optimal sinc interpolation coefficients. >*/


double dsinc (double x);
/*< Return sinc(x) = sin(PI*x)/(PI*x) (double version) >*/


void stoepd (int n, double r[], double g[], double f[], double a[]);
/*< Solve a symmetric Toeplitz linear system of equations Rf=g for f >*/

#endif
