/* This file is automatically generated. DO NOT EDIT! */

#ifndef _vecoper_h
#define _vecoper_h


float dotmultsum( float *xx, float *yy, int n);
/*< dot multiplication of vectors and sum up >*/


void scale( float *xx, float *yy, int n, float s);
/*< implement a scaled indentity operator >*/


void vecabs( float *xx, float *yy, int n);
/*< Absolute value for vector >*/


void scalesum(float *xx, float *yy, float *zz, int n, float sx, float sy);
/*< summation between two scaled vector >*/


void scalesumreal(float *xx, float yy, float *zz, int n, float sx);
/*< summation between one scaled vector and one scaler  >*/


void vecdiv(float *xx, float *yy, float *zz, int n);
/*< division between two vector >*/


void vecmul(float *xx, float *yy, float *zz, int n);
/*< multiplication between two vector >*/


float vecmax(float *xx, int n);
/*< maximum value in a vector >*/


void consvec(float v, int n, float *x);
/*< Create constant-value vector >*/

#endif
